/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "main.h"
#include "ssd1306.h"
#include "bme280.h"
#include "xprintf.h"
#include "delay.h"



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void	GPIO_init(void);


uint8_t	x_adr, y_adr;
int32_t T, H;
uint32_t P;



/*				ToDo
 *
 *		äîäåëàòü delay()
 *
 *
 *
 *
 *
 *
 */


int main(void)
{

	GPIO_init();
	I2C_init(I2C_1);
	delay_init(TIM2);

#ifdef RECEIVER

	I2C_init(I2C_2);
	delay_ms(100);
	BME280_init(I2C_2);

	Displ_init(I2C_1);
	Displ_clear(I2C_1);


	x_adr = 0;
	y_adr = 7;
	X_addr_dspl(x_adr, I2C_1);
	Y_addr_dspl(y_adr, I2C_1);
	ssd1306_write(I2C_1, (uint8_t*)"     ÓËÈ×ÍÛÉ  ÄÀÒ×ÈÊ");


#endif	//RECEIVER




	for(;;)
	{
		GPIOB->BSRR |= LED_red_on;
		delay_ms(1000);
		BME280_read(I2C_2, &T, &H, &P);
		x_adr = 0;
		y_adr = 0;
		X_addr_dspl(x_adr, I2C_1);
		Y_addr_dspl(y_adr, I2C_1);
		xprintf("%ld.%ld C \n%ld.%ld %% \n%d.%d ìì ðò ñò  \n", T / 100, (uint32_t)T % 100, \
				H / 1024, H % 1024 / 10, (int)(P * 3 / 102400), (int)(P * 3 % 102400 / 1000));
		GPIOB->BSRR |= LED_red_off;
		delay_ms(1000);

	}
}

void	GPIO_init(void)
{
	//PA11 - output push-pull 10MHz (SET_pin) for HC-12
	GPIOA->CRH &= ~GPIO_CRH_CNF11_0;
	GPIOA->CRH |= GPIO_CRH_MODE11_0;
	GPIOA->BSRR |= SET_pin_set;

	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPAEN;
	//configure PB12 on output push-pull 2MHz (blinking LED)
	GPIOB->CRH |= GPIO_CRH_MODE12_1;
	GPIOB->CRH &= ~GPIO_CRH_CNF12_0;

	//HC-SR04
	//PA8 - output push-pull 10MHz (Trigger)
//	GPIOA->CRH |= GPIO_CRH_MODE8_0;
//	GPIOA->CRH &= ~GPIO_CRH_CNF8_0;
//	//PA9 - input pull down (Echo)
//	GPIOA->CRH &= ~GPIO_CRH_CNF8_0;
//	GPIOA->CRH |= GPIO_CRH_CNF8_1;
}


